os:
  - linux
  - osx
sudo: false
dist: trusty
language: c
addons:
  apt:
    packages:
    - gobjc
    - libasound2-dev
    - nasm

install:
  - git clone https://github.com/cisco/openh264
  - "cd openh264 && make PREFIX=$HOME/openh264-install && make PREFIX=$HOME/openh264-install install && cd .."

script: "./configure --with-openh264=$HOME/openh264-install && make dep && make"


notifications:
  email: false
  slack:
    rooms:
     - secure: "apknq08JGs+YH2lakKLzBcZ1dtfC62IlBV9gCVoz9iC3FJce52hcSuUmZKHF25ucsBH15cpSB3oloeQTcGIof/dnSAhE+fYrOr+dhJYzKFJYUY0a9srMAW2VSaAt3qsAGIOpZZ4nR6PteRpNpTcsHyZwWYCFuYzL+LqDee74FFhL64ijPk3S+US/6wZuDe61EftFk98WSb5tBKiKFpthkQlN+UTaU51gZg/bydO5+Lp+x/2ecwd10De3F7j773JUKH4lbfd8lyFGxl1/6OLCQA2yWLF9IW2aWPqv1I0fJJmQBUXhw2HaQUfSo76su03J7YxiHg8/gT1vxiSbyZaSwahShbQogl9yYOyk7rqVQYqOpHbC/TBi3bciQaZxzNl6B1q2F0JOzaYIZPDoissXABmbZDqllcW2gg7CWAWQt+Q8cUFETq1+hn4CsJgQWBQo2UcMjie8GT1/rQWRigjk7ryuis03OOJ7VJR2mbDjJoy+bTKs1ZbMLxF4gW8FqVQn9ejPbCMIbnlO0vJgbFUnav9UNmYK3CezoTGO5RIg3k49Ac6wwliCrAcWVSgDp2Ss52sAHNBPSe2EDHavSPijNnkrYbxjz27jXC9Aa3pdbY36fMLD0g7DhqMkU+l6imN/H5E4ibHuGZ9xn8QvlvDBTjgeRIm6epytaHsCue3QMHs="
    on_success: always
